# Generated by Django 3.1.12 on 2022-11-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='warranty',
            new_name='info',
        ),
    ]
